### PR TITLE
PERF-3459 Refactor testcases/simple_query.js

### PR DESCRIPTION
**Pull request by mtandrei**
EDIT forgot the EVG link! Oops

Evergreen: **https://spruce.mongodb.com/version/6373f8bfc9ec44735aa39b97/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC**

Surprisingly, no extra work was needed to get these tests to run (see: [Sort queries](https://spruce.mongodb.com/task/performance_linux_wt_standalone_query_read_commands_patch_6cdad7c65db24d28d5f7b26ea7cece1495ac3dff_6373f8bfc9ec44735aa39b97_22_11_15_20_39_38/trend-charts?execution=0&sortBy=STATUS&sortDir=ASC); [In queries](https://spruce.mongodb.com/task/performance_linux_wt_standalone_query_read_commands_patch_6cdad7c65db24d28d5f7b26ea7cece1495ac3dff_6373f8bfc9ec44735aa39b97_22_11_15_20_39_38/trend-charts?execution=0&sortBy=STATUS&sortDir=ASC);  [Indexed queries](https://spruce.mongodb.com/task/performance_linux_wt_standalone_all_feature_flags_query_read_commands_large_dataset_patch_6cdad7c65db24d28d5f7b26ea7cece1495ac3dff_6373f8bfc9ec44735aa39b97_22_11_15_20_39_38/trend-charts?execution=0&sortBy=STATUS&sortDir=ASC)

Now, a surprise here is that some of the tests appear to have regressed significantly as result of these changes (see Queries.PointQuery_SingleIndex_LL in the [following task](https://spruce.mongodb.com/task/performance_linux_wt_standalone_all_feature_flags_query_read_commands_large_dataset_patch_6cdad7c65db24d28d5f7b26ea7cece1495ac3dff_6373f8bfc9ec44735aa39b97_22_11_15_20_39_38/trend-charts?execution=0&sortBy=STATUS&sortDir=ASC)). I'm not sure what may have caused this; I tried reverting the refactor locally and this doesn't move the needle at all. I'm going to inspect the patch build further. Maybe it's an issue with the additions to utils.js?

### CODE REVIEW

**Review by leozzx — APPROVED** [review]
LGTM, I assume they are all copy-paste so I didn't check every test case in details. It's surprised to have such regression, it seems to be related to `query_read_commands_large_dataset` only. Please figure out the root cause before merging it.

**Comment by mtandrei** [comment]
Evergreen: https://spruce.mongodb.com/version/637e82a53627e0072a207f91/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC 

I reverted spinning indexed queries into their own file and this seems to have gotten rid of the large collection regressions that I was seeing. PTAL when you have the chance.

**Review by leozzx — APPROVED** [review]
LGTM, but do we know the reason why there was 75% regression? Is it because index was not built successfully if we move the function to utils.js?

**Comment by mtandrei** [comment]
Thanks for the review Zixuan! Per offline discussion, I wasn't able to get to the bottom of the cause of the regression (it's a non issue now because the indexed tests are now remaining in 'simple_query.js'

**Pull request merged**
