### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by SqLL**
Hello,

Just wanted to add Dockerfile in order to use mongo-perf without installing python or mongo-shell directly to host.

Give me a feedback when you can, will try to improve it.

### CODE REVIEW

**Comment by henrikingo** [comment]
Thanks. We don't use Docker in our infrastructure, but if it helps you, we're happy to add it.

**Comment by henrikingo** [comment]
Sorry, I completely forgot. Could you please sign our contributor agreement here: https://www.mongodb.com/legal/contributor-agreement

**Comment by SqLL** [comment]
Okay, Normally it's done.
Thanks.

**Comment by henrikingo** [comment]
Thank you very much.

**Pull request merged**
