### PR TITLE
TIG-4208: Update Dockerfile

### PR DESCRIPTION
**Pull request by erfan-mehraban**
- Use python 3
- removed manual mongo installation and used official mongo image
- update mongo version

Tested locally and it was fine.

### CODE REVIEW

**Review by jimoleary — APPROVED** [review]
LGTM.

Ignoreable suggestion: Do you want to link to the official docker hub [page](https://hub.docker.com/_/mongo?tab=description)?

**Review by jimoleary — CHANGES_REQUESTED** [review]
Actually, we will need to get you to submit a contributor agreement to commit this change.

**Comment by erfan-mehraban** [comment]
I just signed it.
I didn't get what you meant by "link to the page". Can you clarify?

**Comment by erfan-mehraban** [comment]
@jimoleary Do you have any update on this?

**Pull request merged**
